version: '3.7'

services:
  bd-school:
    image: mysql
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION",
      ]
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: api
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_ROOT_HOST: "%"
    container_name: "bd-school"
    volumes:
      - school_mysql_data:/var/lib/mysql

volumes:
  school_mysql_data: 

